// Generated by scripts/upload-placement-emojis.js — do not edit by hand.
module.exports = {
  1: { good: '<:placement_1_good:1534566236837380329>', bad: '<:placement_1_bad:1534566238087282758>' },
  2: { good: '<:placement_2_good:1534566239194845255>', bad: '<:placement_2_bad:1534566240364925029>' },
  3: { good: '<:placement_3_good:1534566241476546570>', bad: '<:placement_3_bad:1534566242570997912>' },
  4: { good: '<:placement_4_good:1534566244022222928>', bad: '<:placement_4_bad:1534566245137907812>' },
  5: { good: '<:placement_5_good:1534566246161580045>', bad: '<:placement_5_bad:1534566247352500274>' },
  6: { good: '<:placement_6_good:1534566248493482146>', bad: '<:placement_6_bad:1534566249613361327>' },
  7: { good: '<:placement_7_good:1534566250921857261>', bad: '<:placement_7_bad:1534566251995594823>' },
  8: { good: '<:placement_8_good:1534566252754898945>', bad: '<:placement_8_bad:1534566253845286913>' },
};
