// Generated by scripts/upload-rank-emojis.js — do not edit by hand.
module.exports = {
  iron: '<:rank_iron:1533967125813657655>',
  bronze: '<:rank_bronze:1533967126984003624>',
  silver: '<:rank_silver:1533967127877386511>',
  gold: '<:rank_gold:1533967128493818059>',
  platinum: '<:rank_platinum:1533967133493563393>',
  emerald: '<:rank_emerald:1533969671173177446>',
  diamond: '<:rank_diamond:1533967135498305556>',
  master: '<:rank_master:1533967136480038982>',
  grandmaster: '<:rank_grandmaster:1533967137524154378>',
  challenger: '<:rank_challenger:1533967138522529825>',
};
